# definition of a channel
type Bird::Channel = Struct[{
  'debug'                       => Optional[Variant[Enum['all','off'], String[1]]],
  'table'                       => Optional[String[1]],
  'preference'                  => Optional[String[1]],
  'import'                      => Optional[Variant[Enum['all','none'],String[1]]],
  'export'                      => Optional[Variant[Enum['all','none'],String[1]]],
  'import_keep_filtered'        => Optional[Boolean],
  'rpki_reload'                 => Optional[Boolean],
  'import_limit'                => Optional[Variant[Integer,String[1]]],
  'receive_limit'               => Optional[Variant[Integer,String[1]]],
  'export_limit'                => Optional[Variant[Integer,String[1]]],
  # bgp only:
  'mandatory'                   => Optional[Boolean],
  'next_hop_keep'               => Optional[Variant[Boolean,Enum['ibgp','ebgp']]],
  'next_hop_self'               => Optional[Variant[Boolean,Enum['ibgp','ebgp']]],
  'next_hop_address'            => Optional[String[1]],
  'next_hop_prefer'             => Optional[Enum['global']],
  'gateway'                     => Optional[Enum['direct', 'recursive']],
  'igp_table'                   => Optional[String[1]],
  'import_table'                => Optional[Boolean],
  'export_table'                => Optional[Boolean],
  'export_settle_time'          => Optional[String[1]],
  'secondary'                   => Optional[Boolean],
  'validate'                    => Optional[Boolean],
  'base_table'                  => Optional[String[1]],
  'extended_next_hop'           => Optional[Boolean],
  'require_extended_next_hop'   => Optional[Boolean],
  'add_paths'                   => Optional[Variant[Boolean,Enum['rx','tx']]],
  'require_add_paths'           => Optional[Boolean],
  'aigp'                        => Optional[Variant[Boolean,Enum['originate']]],
  'cost'                        => Optional[Integer],
  'graceful_restart'            => Optional[Boolean],
  'long_lived_graceful_restart' => Optional[Boolean],
  'long_lived_stale_time'       => Optional[Integer],
}]
