# ospf area definition
type Bird::Ospf::Interface = Struct[{
    'cost'                  => Optional[Integer],
    'stub'                  => Optional[Boolean],
    'hello'                 => Optional[Integer],
    'poll'                  => Optional[Integer],
    'retransmit'            => Optional[Integer],
    'priority'              => Optional[Integer],
    'wait'                  => Optional[Integer],
    'dead_count'            => Optional[Integer],
    'dead'                  => Optional[Integer],
    'secondary'             => Optional[Boolean],
    'rx_buffer'             => Optional[Variant[Enum['normal','large'],Integer]],
    'tx_length'             => Optional[Integer],
    'type'                  => Optional[Enum[
        'broadcast', 'bcast', 'pointopoint', 'ptp',
        'nonbroadcast', 'nbma', 'pointomultipoint', 'ptmp'
    ]],
    'link_lsa_suppression'  => Optional[Boolean],
    'strict_nonbroadcast'   => Optional[Boolean],
    'real_broadcast'        => Optional[Boolean],
    'ptp_netmask'           => Optional[Boolean],
    'ptp_address'           => Optional[Boolean],
    'check_link'            => Optional[Boolean],
    'bfd'                   => Optional[Boolean],
    'ttl_security'          => Optional[Variant[Boolean,Enum['tx only']]],
    'tx'                    => Optional[String[1]],
    'tx_priority'           => Optional[Integer],
    'authentication'        => Optional[Enum['none','simple','cryptographic']],
    'password'              => Optional[String[1]],
    'neighbors'             => Optional[Array[String[1]]],
}]
